### ISSUE TITLE
Confuse `diff.conf` and `dracula.conf`

### ISSUE THREAD

**Issue by haunt98** [dracula/kitty#12]
What is the different between 2 files ? I feel confuse

**Comment by keegancsmith** [comment]
Sorry I see we don't document it. `diff.conf` is for https://sw.kovidgoyal.net/kitty/kittens/diff.html#configuration Just place the file in `~/.config/kitty` then `kitty-diff` will have a dracula colour theme.

**Comment by haunt98** [comment]
Thank you for your explanation
