### ISSUE TITLE
Add theme to the kitty themes repo

### ISSUE THREAD

**Issue by TheTrio** [dracula/kitty#15]
There's an [offical kitty themes repo](https://github.com/kovidgoyal/kitty-themes) which powers the kitten for easily [previewing and switching between themes](https://sw.kovidgoyal.net/kitty/kittens/themes/)

I think this theme would be a great addition there.

**Comment by keegancsmith** [comment]
It seems to already be there. https://github.com/kovidgoyal/kitty-themes/blob/master/themes/Dracula.conf althought might be a little different to what we have. You (or anyone else) are welcome to contribute to that repo and link back to here.

**Comment by TheTrio** [comment]
Yes I did see that and it is indeed a lot different from the one here. I might name this theme dracula official or something to not have two themes named dracula. I hope that's ok. 

Thanks!

**Comment by TheTrio** [comment]
So the existing Dracula theme in that repo has been [removed and this one has been added](https://github.com/kovidgoyal/kitty-themes/pull/1) Am closing this issue now. On a related note, perhaps the instructions should be updated to reflect this. Makes it much easier to install the theme

**Comment by keegancsmith** [comment]
Thanks for the fast turnaround!
