### ISSUE TITLE
Shell comments are unreadable in zsh shell

### ISSUE THREAD

**Issue by sandorex** [dracula/kitty#5]
![Screenshot](https://user-images.githubusercontent.com/18004075/78976706-036a8c00-7b17-11ea-8a36-f5a013d9704f.png)

**Comment by keegancsmith** [comment]
@sandorex Can you share your full kitty configuration? I can't reproduce with my configuration.

**Comment by sandorex** [comment]
And kitty version is 
```
❯ kitty --version 
kitty 0.17.2 created by Kovid Goyal
```
The dracula.conf is download from the repo of course
```
❯ cat ~/.config/kitty/kitty.conf               
# coloring
include themes/dracula.conf

# fonts
font_family             Hack Nerd Font
font_size               16
bold_font               auto
italic_font             auto
bold_italic_font        auto

enable_audio_bell       no
remember_window_size    no
bell_on_tab             yes
initial_window_width    70c
initial_window_height   20c
```

This also may have something to do with how `zsh` colors the comments

**Comment by sandorex** [comment]
This issue only exists in zsh shell why i dont know, but here's a fix if anybody encounters this

Create a file `dracula-modified.conf`
```
# include the original theme
include dracula.conf

# modify the black color so the comments are visible
color0  #6d6d6d
```
and then include this file instead of `dracula.conf` like
```diff
-include dracula.conf
+include dracula-modified.conf
```

**Comment by keegancsmith** [comment]
I am also using the zsh shell with this theme, and couldn't replicate this using your configuration. Are you using the latest version of dracula.conf? It was updated a while ago, but just want to check that. I am guessing it is likely a differences in how your ZSH is configured vs mine? Not sure.

I don't think we can take the suggested modification, since we are using the spec's version for color0.

**Comment by sandorex** [comment]
I feel so stupid, the issue was with [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting)...

**Comment by keegancsmith** [comment]
No worries :) Glad you found the cause!

**Comment by sandorex** [comment]
For anybody that has the same issue here's the real fix, add this to your zshrc **after loading zsh-syntax-highlighting**
```sh
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[comment]='fg=#6272a4'
```
