### ISSUE TITLE
kitty diff?

### ISSUE THREAD

**Issue by screendriver** [dracula/kitty#6]
Is there already something existent for [kitty diff colors](https://sw.kovidgoyal.net/kitty/kittens/diff.html#colors)?	`kitty diff` is using [Pygments](https://pygments.org) under the hood	to colorize the output that can be customised in a [diff.conf](https://sw.kovidgoyal.net/kitty/kittens/diff.html#configuration).

**Comment by keegancsmith** [comment]
I'm unaware, but happy to accept/review a PR adding a first attempt at it :)
